dotenv: .env


networks:
    default: rinkeby-geth
    goerli-geth:
        verify: false
    rinkeby-geth:
        verify: false

console:
    show_colors: true
    color_style: manni

project_structure:
    contracts: brownie-contracts